# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MjEwMmE0NTQxZmU2YTNhN2IzMzFhN2U2MzU0ZTI5ZTEwNDYyOThlMmI0YmQ2NzZmNDJjOTZlMjJhZjgwMjBmZDBiNTdjODRmM2JiNjM0YjQ2MjIzMGI5ZDMzNGQ0ZTJiMmIwM2JlMDU5NzMwNGEyNTJlODQ2ZTVkNWE2NDhlZGM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
